### ISSUE TITLE
Get the dates from fixturedownload.com

### ISSUE THREAD

**Issue by emavgl** [mpellicc/fanta-formazioni-reminder#2]
Hello, I had the same problem and I ended up finding this project. Great work!

If I can propose an improvement - I have found this website where you can get a JSON with the Serie A calendar: https://fixturedownload.com/results/serie-a-2023 - maybe you can fetch the next dates from here.

**Comment by mpellicc** [comment]
Thank you for the appreciation and the suggestion! I don't have much time as when I first started the project, but I'll look into it.
